name: Build and Run Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t assignment_uzabase . | tee build_log.txt

      - name: Upload Build Log Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: build_log.txt

      - name: Run Docker Container
        run: |
          docker run --name uzabase_container -d assignment_uzabase /bin/bash script/run.sh

      - name: Display Running Containers
        run: docker ps -a
