name: Build and Run Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t assignment_uzabase .

      - name: Build Docker image | Generate Docker build log
        run: |
          docker build -t assignment_uzabase . > Docker_build.txt 2>&1


      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: Docker_build.txt

      - name: Run Docker Container (bash run.sh)
        run: |
          docker run --rm assignment_uzabase /bin/bash -c "cd script && bash run.sh"

      - name: Get pip list from Docker container
        run: |
          # Run the container again and get the pip list
          docker run --rm assignment_uzabase /bin/bash -c "pip list" > pip_list.txt

      - name: Upload pip list
        uses: actions/upload-artifact@v4
        with:
          name: pip-list
          path: ./pip_list.txt

      - name: Display Running Containers
        run: docker ps -a
