name: Build and Run Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t assignment_uzabase .

      - name: Build Docker image | Generate Docker build log
        run: |
          docker build -t assignment_uzabase . | tee Docker_build.txt


      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: Docker_build.txt


      - name: Run Docker Container
        run: |
          # Run the Docker container in detached mode
          docker run -d --name uzabase_container assignment_uzabase /bin/bash -c "cd script && bash run.sh"

      - name: Get pip list from Docker container
        run: |
          # Generate pip list inside the container and store it in a file
          docker exec uzabase_container bash -c "pip list > /app/pip_list.txt"

          # Copy the pip_list.txt from the container to the local runner
          docker cp uzabase_container:/app/pip_list.txt ./pip_list.txt

          # Stop and remove the container after retrieving the pip list
          docker rm -f uzabase_container

      - name: Upload pip list
        uses: actions/upload-artifact@v4
        with:
          name: pip-list
          path: ./pip_list.txt

      - name: Display Running Containers
        run: docker ps -a
